### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by KG3RK3N** [nativescript-community/ui-mapbox#10]
Hey guys, I would love to contribute more the plugin which is why I'm asking for a roadmap. 😃 

My current todo list for this project:
- Full expression support for layout / paint properties
- Support for raster source & layer
- More features are welcome 😄 

I think we should create a small roadmap to know which features are desired and should implemented.

**Comment by keerl** [comment]
I would suggest making a GitHub project at the Community level: https://github.com/orgs/nativescript-community/projects

That way we can easily track goals of the project and keep track of its progress.

I am working on a standard community plugin seed that contains demos for all 4 frameworks (Angular, Vue, Svelte, and React) and a more standard plugin development workflow including Detox end-to-end testing.

Once I am finished with it, I want to apply it to this plugin (as well as all the others).

**Comment by keerl** [comment]
I made a project for it here: https://github.com/orgs/nativescript-community/projects/4

It's all Issues based, so whenever you make one, in the sidebar select the project ui-mapbox

**Comment by cvietor** [comment]
Thanks, @keerl !
Regarding the changes towards the community plugin seed, let's discuss that in a separate issue :-)

**Comment by cvietor** [comment]
added link to project board to readme
