### ISSUE TITLE
Blue circle color change of when showUserLocation is active?

### ISSUE THREAD

**Issue by butaminas** [nativescript-community/ui-mapbox#15]
I have the setting `showUserLocation` as true. This shows a little blue circle on the map to indicate user location.

Is there any way to change the blue color or the icon itself?

**Comment by cvietor** [comment]
At the moment, that is not possible. your best bet for modifying the user location marker is to manually call the `showUserLocationMarker` method and pass an options object to it. the `showUserLocation` attribute uses the aforementioned `showUserLocationMarker` method with an empty options object passed.

but even with that, support for properties is quite limited, as (quote from [sourcecode](https://github.com/nativescript-community/ui-mapbox/blob/master/src/mapbox.android.ts#L2715)):

```
     * Supported options are:
     *
     * - elevation
     * - accuracyColor
     * - accuracyAlpha
     * - useDefaultLocationEngine
     * - renderMode
     * - cameraMode
     * - clickListener
     * - cameraTrackingChangeListener
```

for iOS, it's even worse:

```
     * Supported options under iOS are:
     *
     * - renderMode
     * - cameraMode
     * - clickListener
```

**Comment by butaminas** [comment]
So it makes more sense to use a regular marker and not to use the `showUserLocation` parameter.  
However, if I set `showUserLocation` to false and try to use the `getUserLocation()` method, it doesn't work.  
 

In this case, should use something else (e.g. `nativescript-geolocation`) to get user coordinates or is there another method that is available within `ui-mapbox` for getting user location?  
  
Thanks.

**Comment by cvietor** [comment]
hm i can see an issue here :-)
if you add your `MapView` instance via markup and set `showUserLocation` to false, `getUserLocation` won't work because under the hood, the `LocationComponent` is not setup, which is done in on initialization, when setting `showUserLocation` to true :-)

did you try to call the `showUserLocationMarker` method and afterwards `getUserLocation` ?

**Comment by butaminas** [comment]
If I run `getUserLocation` right after `showUserLocationMarker` then it works but the coordinates are `-180, -180`

If run it inside `.then()` - `getUserLocation` doesn't work with no crash.

**Comment by cvietor** [comment]
something seems weird, that is working perfectly fine for me:

```
        this.mapbox
            .showUserLocationMarker({})
            .then(() => {
                this.mapbox.getUserLocation().then((loc) => {
                    console.log('loc :', loc);
                });
            })
            .catch((error: string) => {
                console.log('mapbox getUserLocation error: ' + error);
            });
```

**Comment by cvietor** [comment]
will add support for additional properties, so you can set foreground and background-color

**Comment by cvietor** [comment]
you can change the user location dot's color, stale-color, background-color and bearingtilt color on android with version `6.2.0`
