### ISSUE TITLE
NS7 Vue addLayer not working

### ISSUE THREAD

**Issue by sivo1981** [nativescript-community/ui-mapbox#2]
The problem is with method "addLayer" because of internal call to "this.addSource(sourceId, style.source)" and in this method there is condition which is not meet.

`addSource(id, options, nativeMap)`
nativeMap argument is always undefined because it is not called from the calling function.

```
const theMap = nativeMap;
let source;
if (!theMap) {
  reject('No map has been loaded');
  return;
}
```

Reject is always firing.

**Comment by farfromrefug** [comment]
@sivo1981 will need a bit more. I dont see what line you are talking about. Where is the issue?

**Comment by sivo1981** [comment]
I have replaced calling method "addLayer" with "addPolyline" which is working as expected.
