### ISSUE TITLE
Same icon for all markers added

### ISSUE THREAD

**Issue by j99ht** [nativescript-community/ui-mapbox#32]
Installing the latest release of the plugin, 6.2.8, when I add an array of markers, with different icons, the markers are drawn with the icon of the first one.
I'm using NS7+Angular.
See below a piece of code.
```
       
 this.myarray.forEach((element) => {
          const markerElement = this.myservice.setElementMarker(element);  // It returns a mapbox marker
          this.parkingMap.addMarkers([markerParking]);
        });
```
I see all the properties of the markers correctly set (title, subtitle, etc) but the icon displayed is always the one of the first element drawn.

I have tried with older releases of the package (6.0.0) for example, and it works correctly.

**Comment by j99ht** [comment]
It works with the solution proposed.

**Comment by rlnd1** [comment]
Any update on this?

**Comment by Sauvetonbio** [comment]
Same issue on 6.2.9 how can we do ? Thank you

**Comment by rlnd1** [comment]
Could someone have a look at the open PR?
