### ISSUE TITLE
how can i set language?

### ISSUE THREAD

**Issue by CyrusLiu158** [nativescript-community/ui-mapbox#40]
I want to set  chinese by default。somebody konws how to accomplish it ?
I found the plugin  [mapbox-gl-language ](https://github.com/mapbox/mapbox-gl-language) , but no nativescript version.
need help, thx.

**Comment by KG3RK3N** [comment]
I've just opened a new PR #42 that makes it possible to set and get the layer properties.

After the PR is merged, you can set the language with the sample below:
```typescript

const lang = 'en'; // 'ar', 'de', 'en', 'es', 'fr', 'it', 'ja', 'ko', 'mul', 'pt', 'ru', 'zh-Hans', 'zh-Hant'
const mapLayers = await this.mapbox.getLayers();
mapLayers
    .filter((layer) => !!layer.getProperty('text-field'))
    .forEach((layer) => {
        layer.setProperty('text-field', ['get', `name_${lang}`]);
    });
```

**Comment by CyrusLiu158** [comment]
thx
