### ISSUE TITLE
feature: getLayer / getLayers

### ISSUE THREAD

**Issue by cvietor** [nativescript-community/ui-mapbox#5]
**Is your feature request related to a problem? Please describe.**
Currently, the ui-mapbox plugin does not allow to get (and interact) with map style layers.
A use case would be to show or hide certain layers like "hide motorways", "show bikelanes"

**Describe the solution you'd like**
I propose to introduce the concept of a "Layer" type as following:
```
interface Layer {
  id: string;
  visibility(): boolean;
  show(): void;
  hide(): void;
}
```
The native SDKs for Android and iOS provide more properties, but additional properties can be added later when needed (i.e. getMaxZoom, getMinZoom, etc). For now, imho that basic structure should be good enough for now.

To be able to get a single layer or a list of all map style layers, the `MapboxViewApi` needs to be extended with the following methods:
```
getLayer(name: string, nativeMap?): Promise<Layer>;

getLayers(nativeMap?: any): Promise<Array<Layer>>;
```

**Additional context**
I would be happy to provide a PR that adds this functionality

**Comment by farfromrefug** [comment]
@cvietor great idea! waiting for your PR ;)

**Comment by felixkrautschuk** [comment]
@cvietor @farfromrefug maxZoom and minZoom have already been implemented in my PR [here](https://github.com/Yermo/nativescript-mapbox/pull/365) in the original nativescript-mapbox plugin. But unfortunately the plugin author never merged it for whatever reason :(

**Comment by farfromrefug** [comment]
@felixkrautschuk any chance for you to create the PR again on this repo ? I will merge it!

**Comment by felixkrautschuk** [comment]
@farfromrefug not immediatly, but maybe at the weekend

**Comment by cvietor** [comment]
@felixkrautschuk actually, the getMinZoom and getMaxZoom methods i mentioned are layer dependent and your's are the min- and max zoom levels of the map... so they a different things. 
anyway, PR is welcomed :-)

**Comment by felixkrautschuk** [comment]
@cvietor ahhhh sorry :D 
but yeah, i will recreate that PR anyway as soon as i get time
