### ISSUE TITLE
Rotating markers

### ISSUE THREAD

**Issue by syonfabian** [nativescript-community/ui-mapbox#6]
Is there any property such as the angle for rotating markers?

Forwarded from https://github.com/Yermo/nativescript-mapbox/issues/337#issuecomment-733168768.

**Comment by cvietor** [comment]
@syonfabian afaik there is no property in the mapbox sdk that supports rotating markers (might be missing something) when using the `PointAnnotation` (iOS) / `Marker` (Android) types, which are utilised for the `addMarkers` function at the moment.

Quote from the docs:
`In summary, using annotations provide a familiar interface to MapKit’s annotation implementation, with built-in dragging and selection support. But, it is not recommended if you need to add a large number of annotations to a map, or if you also need to style different annotations based on a specific data property - consider using our more performant MGLStyleLayer classes, detailed below.`
[iOS Docs - Using annotations](https://docs.mapbox.com/ios/maps/overview/markers-and-annotations/#using-annotations)

So i believe the `StyleLayer` would be the appropriate method for adding markers with a bit more options. Unfortunately, StyleLayers are currently not implemented. I'll currently looking into fixing current addLayer function plus adding support for more layer types (currently, only `line` and `circle` are supported)

**Comment by syonfabian** [comment]
Thanks!
Yeah, I have seen that only these two are supported. 
Would be awesome if you can extend the options.

**Comment by cvietor** [comment]
We recently added support for fill, symbol and raster layers. We will release a new version (hopefully very) soon.
In the meanwhile, you could have a look into the demo app to see how you can [add a symbol layer](https://github.com/nativescript-community/ui-mapbox/blob/master/demo/app/main-view-model.ts#L565) (rotation would need a `icon-rotate` key-value pair in the `layout` property.

**Comment by syonfabian** [comment]
Thank you @cvietor! I will give it a try!

**Comment by cvietor** [comment]
try release 6.1.0 (out on npm right now), should be resolved with that one.
