### ISSUE TITLE
Error when trying to build for release (iOS)

### ISSUE THREAD

**Issue by Reached** [nativescript-community/ui-mapbox#60]
Hi there,

I am trying to build my app for release on iOS, but I keep running into the same issue:

```
Cannot get final name for export '__esModule' of ./node_modules/@nativescript-community/ui-mapbox/mapbox.ios.js
while generating the root export '__esModule' (used name: '__esModule')
```

Version: latest (6.2.11), but I also tried earlier versions

Build command:

`ns build ios --release --env.production`

Any help is appreciated!

**Comment by keerl** [comment]
From the error message it looks like an old version. Have you done a `ns clean` before building with the latest version?

I just ran `ns build ios --release --env.production` on the latest version and it worked fine for me.

**Comment by Reached** [comment]
Yea I tried that actually, but still the same error occurs.

I tried:

`ns prepare ios --release`
`ns build ios --release --env.uglify --env.production`

It seems to be super random, I had it running yesterday after trying to up and downgrade the version a couple of times and then rebuild... But now it does not seem to work again

**Comment by Reached** [comment]
Okay, so I finally got it to build using 6.2.11, but now I am unable to tap on my markers (this definitely works in previous versions of the plugin, but not the latest for some reason)....

**Comment by Reached** [comment]
Update, markers seem to work on Android, but not on iOS

**Comment by Reached** [comment]
Any ideas here? Seems there are issues with the markers on iOS in the latest version, but earlier versions is not possible for me to build..

**Comment by keerl** [comment]
Just published 6.2.12. Could you try that out?

**Comment by Reached** [comment]
Will do thanks!

**Comment by Reached** [comment]
It works like a charm now (both building, and markers), thanks for fixing it so fast, and for helping out in general!
