### ISSUE TITLE
[Bug][Android]: missing current user location on map

### ISSUE THREAD

**Issue by foxgreek** [nativescript-community/ui-mapbox#84]
Hello there,

we are using mapbox for showing multiple markers on our app. It runs on android and iOS. Everything worked well, but since some weeks we are not able to get the current location on android. It already worked and we did not update the app since then. Any ideas why the current location can't be found?

We already requested ACCESS_COARSE_LOCATION and ACCESS_FINE_LOCATION in AndroidManifest and of course activated the currentUserLocation with showUserLocation="true"

Thanks for your help!

**Comment by felixkrautschuk** [comment]
I also had this issue on Android 12+.

I added this dependency to my app.gradle and after that, it was working again:

```
dependencies {
    implementation "com.google.android.gms:play-services-location:19.0.1"
}
```

**Comment by foxgreek** [comment]
@felixkrautschuk thank you once again! It's working now again
