### ISSUE TITLE
Call to getLayer() throws the error "TypeError: Cannot read property 'identifier' of null" [iOS only]

### ISSUE THREAD

**Issue by seros00** [nativescript-community/ui-mapbox#88]
Calling getLayer("MylayerID") throws the error "TypeError: Cannot read property 'identifier' of null" when the layer doesn't exists.

My config:
iOS: 15.4
iPhone 12 (emulated)
NS: 8.2.3
ui-mapbox: 6.2.15

**Comment by guillemc23** [comment]
This is happening to me on Android too, I opened #89 to explain more in detail what happened to me.

**Comment by farfromrefug** [comment]
@seros00 @guillemc23 sorry for the long delay. A new version has been published which should fix this.
